### ISSUE TITLE
Astro 5 support

### ISSUE THREAD

**Issue by anotheri** [ktym4a/astro-page-insight#148]
When i install the package to astro 5 project, i get this warning:

> astro is listed by your project with version 5.0.0-beta.5 (peec57), which doesn't satisfy what astro-page-insight and other dependencies request (^4.16.7 || ^4.16.7).

Otherwise everything works as expected to me. So please update `peerDependencies`.

**Comment by ktym4a** [comment]
@anotheri 
Thanks.
I just updated `peerDependencies` and already release new version (v0.9.0).

I think everything going to work well, but if anything happens please let me know.
